###############################################################
#  Generated by:      Cadence Innovus 15.23-s045_1
#  OS:                Linux x86_64(Host ID ieng6-ece-05.ucsd.edu)
#  Generated on:      Fri Mar 21 19:38:59 2025
#  Design:            sram_w16_out
#  Command:           floorPlan -s 700 100 15 15 15 15
###############################################################

Version: 8

Head Box: 0.0000 0.0000 208.0550 207.0000
IO Box: 0.0000 0.0000 208.0550 207.0000
Core Box: 0.0000 0.0000 208.0550 207.0000
UseStdUtil: false

######################################################
#  DesignRoutingHalo: <space> <bottomLayerName> <topLayerName>
######################################################

######################################################
#  Core Rows Parameters:                             #
######################################################
Row Spacing = 0.000000
Row SpacingType = 2
Row Flip = 2
Core Row Site: core 

##############################################################################
#  DefRow: <name> <site> <x> <y> <orient> <num_x> <num_y> <step_x> <step_y>  #
##############################################################################
DefRow: ROW_0 core 0.0000 0.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_1 core 0.0000 1.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_2 core 0.0000 3.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_3 core 0.0000 5.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_4 core 0.0000 7.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_5 core 0.0000 9.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_6 core 0.0000 10.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_7 core 0.0000 12.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_8 core 0.0000 14.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_9 core 0.0000 16.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_10 core 0.0000 18.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_11 core 0.0000 19.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_12 core 0.0000 21.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_13 core 0.0000 23.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_14 core 0.0000 25.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_15 core 0.0000 27.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_16 core 0.0000 28.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_17 core 0.0000 30.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_18 core 0.0000 32.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_19 core 0.0000 34.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_20 core 0.0000 36.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_21 core 0.0000 37.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_22 core 0.0000 39.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_23 core 0.0000 41.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_24 core 0.0000 43.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_25 core 0.0000 45.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_26 core 0.0000 46.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_27 core 0.0000 48.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_28 core 0.0000 50.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_29 core 0.0000 52.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_30 core 0.0000 54.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_31 core 0.0000 55.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_32 core 0.0000 57.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_33 core 0.0000 59.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_34 core 0.0000 61.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_35 core 0.0000 63.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_36 core 0.0000 64.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_37 core 0.0000 66.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_38 core 0.0000 68.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_39 core 0.0000 70.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_40 core 0.0000 72.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_41 core 0.0000 73.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_42 core 0.0000 75.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_43 core 0.0000 77.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_44 core 0.0000 79.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_45 core 0.0000 81.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_46 core 0.0000 82.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_47 core 0.0000 84.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_48 core 0.0000 86.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_49 core 0.0000 88.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_50 core 0.0000 90.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_51 core 0.0000 91.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_52 core 0.0000 93.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_53 core 0.0000 95.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_54 core 0.0000 97.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_55 core 0.0000 99.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_56 core 0.0000 100.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_57 core 0.0000 102.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_58 core 0.0000 104.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_59 core 0.0000 106.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_60 core 0.0000 108.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_61 core 0.0000 109.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_62 core 0.0000 111.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_63 core 0.0000 113.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_64 core 0.0000 115.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_65 core 0.0000 117.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_66 core 0.0000 118.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_67 core 0.0000 120.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_68 core 0.0000 122.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_69 core 0.0000 124.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_70 core 0.0000 126.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_71 core 0.0000 127.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_72 core 0.0000 129.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_73 core 0.0000 131.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_74 core 0.0000 133.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_75 core 0.0000 135.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_76 core 0.0000 136.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_77 core 0.0000 138.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_78 core 0.0000 140.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_79 core 0.0000 142.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_80 core 0.0000 144.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_81 core 0.0000 145.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_82 core 0.0000 147.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_83 core 0.0000 149.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_84 core 0.0000 151.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_85 core 0.0000 153.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_86 core 0.0000 154.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_87 core 0.0000 156.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_88 core 0.0000 158.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_89 core 0.0000 160.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_90 core 0.0000 162.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_91 core 0.0000 163.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_92 core 0.0000 165.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_93 core 0.0000 167.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_94 core 0.0000 169.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_95 core 0.0000 171.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_96 core 0.0000 172.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_97 core 0.0000 174.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_98 core 0.0000 176.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_99 core 0.0000 178.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_100 core 0.0000 180.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_101 core 0.0000 181.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_102 core 0.0000 183.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_103 core 0.0000 185.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_104 core 0.0000 187.2000 FS 1040 1 0.2000 0.0000
DefRow: ROW_105 core 0.0000 189.0000 N 1040 1 0.2000 0.0000
DefRow: ROW_106 core 0.0000 190.8000 FS 1040 1 0.2000 0.0000
DefRow: ROW_107 core 0.0000 192.6000 N 1040 1 0.2000 0.0000
DefRow: ROW_108 core 0.0000 194.4000 FS 1040 1 0.2000 0.0000
DefRow: ROW_109 core 0.0000 196.2000 N 1040 1 0.2000 0.0000
DefRow: ROW_110 core 0.0000 198.0000 FS 1040 1 0.2000 0.0000
DefRow: ROW_111 core 0.0000 199.8000 N 1040 1 0.2000 0.0000
DefRow: ROW_112 core 0.0000 201.6000 FS 1040 1 0.2000 0.0000
DefRow: ROW_113 core 0.0000 203.4000 N 1040 1 0.2000 0.0000
DefRow: ROW_114 core 0.0000 205.2000 FS 1040 1 0.2000 0.0000

############################################################################################
#  Track: dir start number space layer_num layer1 [firstColor] [isSameColor] [width] [rule]#
############################################################################################
Track: Y 0.8000 258 0.8000 1 8
Track: X 0.9000 259 0.8000 1 8
Track: X 0.1000 1040 0.2000 1 7
Track: Y 0.8000 258 0.8000 1 7
Track: Y 0.2000 1034 0.2000 1 6
Track: X 0.1000 1040 0.2000 1 6
Track: X 0.1000 1040 0.2000 1 5
Track: Y 0.2000 1034 0.2000 1 5
Track: Y 0.2000 1034 0.2000 1 4
Track: X 0.1000 1040 0.2000 1 4
Track: X 0.1000 1040 0.2000 1 3
Track: Y 0.2000 1034 0.2000 1 3
Track: Y 0.2000 1034 0.2000 1 2
Track: X 0.1000 1040 0.2000 1 2
Track: X 0.1000 1040 0.2000 1 1
Track: Y 0.2000 1034 0.2000 1 1

######################################################
#  GCellGrid: dir start number space                 #
######################################################
GCellGrid: X 206.1000 2 1.9550
GCellGrid: X 0.1000 104 2.0000
GCellGrid: X 0.0000 2 0.1000
GCellGrid: Y 206.2000 2 0.8000
GCellGrid: Y 0.2000 104 2.0000
GCellGrid: Y 0.0000 2 0.2000

######################################################
#  SpareCell: cellName                               #
#  SpareInst: instName                               #
######################################################

###############################1p########################
#  <SelectiveBlockage>                                #
#     <cell name="cell_name" />                     #
#  </SelectiveBlockage                                #
#######################################################

######################################################
#  ScanGroup: groupName startPin stopPin             #
######################################################

######################################################
#  JtagCell:  leafCellName                           #
#  JtagInst:  <instName | HInstName>                 #
######################################################

#########################################################
#  PhysicalNet: <name> [-pwr|-gnd|-tiehi|-tielo]        #
#########################################################
PhysicalNet: VDD -pwr
PhysicalNet: VSS -gnd

#########################################################
#  PhysicalInstance: <name> <cell> <orient> <llx> <lly> #
#########################################################

#####################################################################
#  Group: <group_name> <nrHinst> [-isPhyHier]                       #
#    <inst_name>                                                    #
#    ...                                                            #
#####################################################################

#####################################################################
#  Fence:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Region: <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  Guide:  <name> <llx> <lly> <urx> <ury> <nrConstraintBox>         #
#    ConstraintBox: <llx> <lly> <urx> <ury>                         #
#    ...                                                            #
#  SoftGuide: <name>                                                #
#    ...                                                            #
#####################################################################

###########################################################################
#  <Constraints>                                                          #
#     <Constraint  type="fence|guide|region|softguide"                    #
#                  readonly=1  name="blk_name">                           #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#     </Constraint>                                                       #
#  </Constraints>                                                         #
###########################################################################
###########################################################################
#  <HierarchicalPartitions>                                               #
#     <GlobalPinConstraints>                                              #
#         <PinSpacing spacing=val />                                      #
#         <PinWidth layer=layerId width=val />                            #
#         <PinDepth layer=layerId depth=val />                            #
#         <CornerToPinDistance distance=val />                            #
#     </GlobalPinConstraints>                                             #
#     <NetGroup name="group_name" nets=val spacing=val isOptOrder=val   #
#         isAltLayer=val isPffGroup=val isSpreadPin=val                   #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val isMixedSignal=val >         #
#         <Net name="net_name" /> ...                                   #
#     </NetGroup>                                                         #
#     <Partition name="ptn_name"  hinst="name"                            #
#         coreToLeft=fval coreToRight=fval coreToTop=fval                 #
#         coreToBottom=val pinSpacingNorth=val pinSpacingWest=val         #
#         pinSpacingSouth=val pinSpacingEast=val  blockedLayers=xval >    #
#         <TrackHalfPitch Horizontal=val Vertical=val />                  #
#         <SpacingHalo left=10.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <Clone hinst="hinst_name" orient=R0|R90|... />                  #
#         <PinLayer side="N|W|S|E" Metal1=yes Metal2=yes ... />           #
#         <RowSize cellHeight=1.0 railWidth=1.0 />                        #
#         <DefaultTechSite name="core" />                                   #
#         <RoutingHalo sideSize=11.0 bottomLayer=M1 topLayer=M2  />       #
#         <SpacingHalo left=11.0 right=11.0 top=11.0 bottom=11.0 />       #
#         <PinToCornerDistance  totalCorners=nrCorners >                  #
#            <Corner number=<cornerNumber> distance=<distance> /> ...     #
#         </PinToCornerDistance >                                         #
#         <PinSpacingArea llx=val lly=val urx=val ury=val spacing=val />  #
#         <LayerWidthDepth layer=layerId width=w depth=d />               #
#         <PinConstraint>                                                 #
#            <Pin name="pinName" >                                      #
#               <edge2 edgeMap=val />                                    #
#               <spacing space=val />                                    #
#               <layer layerMap=xval />                                  #
#               <pinWidth width=val />                                   #
#               <pinDepth depth=val />                                   #
#               <location x=val y=val />                                 #
#            </Pin>                                                       #
#         </PinConstraint>                                                #
#     </Partition>                                                        #
#     <CellPinGroup name="group_name" cell="cell_name" pins=nr        #
#         spacing=val isOptOrder=val isAltLayer=val isSpreadPin=val       #
#         isExcludeAllLayer=val isExcludeSameLayer=val keepOutDistance=val#
#         isPureExclude=val isCompactArea=val >                           #
#         <GroupFTerm name="term_name" /> ...                             #
#     </CellPinGroup>                                                     #
#     <PartitionPinBlockage layerMap=x llx=1 lly=2 urx=3 ury=4 name="n" />#
#     <PinGuide name="name" boxes=num layerPriority=val cell="name" >     #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 layer=id /> ...         #
#     </PinGuide>                                                         #
#     <CellPtnCut name="name" cuts=Num >                                  #
#        <Box llx=11.0 lly=22.0 urx=33.0 ury=44.0 /> ...                  #
#     </CellPtnCut>                                                       #
#  </HierarchicalPartitions>                                              #
###########################################################################
<HierarchicalPartitions>
    <GlobalPinConstraints>
        <PinSpacing spacing=2 />
        <CornerToPinDistance distance=5 />
    </GlobalPinConstraints>
    <Partition name="sram_w16_out" hinst="" coreToLeft=0.0000 coreToRight=0.0000 coreToTop=0.0000 coreToBottom=0.0000 pinSpacingNorth=-1 pinSpacingWest=-1 pinSpacingSouth=-1 pinSpacingEast=-1 blockedLayers=0xff orient=R0>
	<PinLayer side="N" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="W" Metal3=yes Metal5=yes Metal7=yes />
	<PinLayer side="S" Metal2=yes Metal4=yes Metal6=yes Metal8=yes />
	<PinLayer side="E" Metal3=yes Metal5=yes Metal7=yes />
    <PinToCornerDistance totalCorners=4 >
      <Corner number=0 distance=-1 />
      <Corner number=1 distance=-1 />
      <Corner number=2 distance=-1 />
      <Corner number=3 distance=-1 />
    </PinToCornerDistance>
    </Partition>
</HierarchicalPartitions>

######################################################################################
#  BlackBox: -cell <cell_name> { -size <x> <y> |  -area <um^2> | \                  #
#            -gatecount <count> <areapergate> <utilization> | \                     #
#            {-gateArea <gateAreaValue> [-macroArea <macroAreaValue>]} } \          #
#            [-minwidth <w> | -minheight <h> | -fixedwidh <w> | -fixedheight <h>] \ #
#            [-aspectratio <ratio>]                                                  #
#            [-boxList <nrConstraintBox>                                             #
#              ConstraintBox: <llx> <lly> <urx> <ury>                                #
#              ... ]                                                                 #
######################################################################################

#######################################################################################
#  <Blackboxes>                                                                       #
#     <Blackbox  cell=name  width=N height=N                                          #
#                { area=A | gatecount=N areaPerGate=A cellUtil=F |                    #
#                  gateArea=F {macroArea=F | macorList='str'} includeMacroArea={0|1}} #
#                [minWidth=N | minHeight=N | fixedWidh=N | fixedHeight=N]             #
#                [aspectRatio=R] >                                                    #
#         <Box llx=float lly=float urx=float ury=float /> ...                         #
#     </Blackbox>                                                                     #
#  </Blackboxes>                                                                      #
#######################################################################################

######################################################
#  Instance: <name> <orient> <llx> <lly>             #
######################################################

#################################################################
#  Block: <name> <orient> [<llx> <lly>]                         #
#         [<haloLeftMargin>  <haloBottomMargin>                 #
#          <haloRightMargin> <haloTopMargin> <haloFromInstBox>] #
#         [<IsInstDefCovered> <IsInstPreplaced>]                #
#                                                               #
#  Block with INT_MAX loc is for recording the halo block with  #
#  non-prePlaced status                                         #
#################################################################

######################################################
#  BlockLayerObstruct: <name> <layerX> ...           #
######################################################

######################################################
#  FeedthroughBuffer: <instName>                     #
######################################################

####################################################################################
#  <PlacementBlockages>                                                            #
#     <Blockage name="blk_name" type="hard|soft|partial">                      #
#       <Attr density=1.2 excludeFlops=yes inst="inst_name" pushdown=yes />      #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                        #
#     </Blockage>                                                                  #
#  </PlacementBlockages>                                                           #
####################################################################################

#################################################################
#  <SizeBlockages>                                             #
#     <Blockage name="blk_name">                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                     #
#     </Blockage>                                               #
#  </SizeBlockages>                                            #
#################################################################

##########################################################################################################
#  <RouteBlockages>                                                                                      #
#     <Blockage name="blk_name" type="User|RouteGuide|PtnCut|WideWire">                              #
#       <Attr spacing=1.2 drw=1.2 inst="name" pushdown=yes fills=yes exceptpgnet=yes pgnetonly=yes />  #
#       <Layer type="route|cut|masterslice" id=layerNo />                                              #
#       <Box llx=1 lly=2 urx=3 ury=4 /> ...                                                              #
#       <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...  />                                                      #
#     </Blockage>                                                                                        #
#  </RouteBlockages>                                                                                     #
##########################################################################################################

######################################################
#  NetWeight: <net_name> <weight (in integer)>       #
######################################################

###########################################################################################
# NetbottomPreferredRoutingLayer:  <net_name> <bottomPreferredRoutingLayer (in integer)>  #
###########################################################################################

################################################################
# NetAvoidDetour:  <net_name>  < avoidDetour  { 1| 0}>   #
################################################################

#################################################################
#  SprFile: <file_name>                                         #
#################################################################
SprFile: .sram_w16_out23534.rs.fp.spr

##############################################################################
#  <IOPins>                                                                  #
#    <Pin name="pin_name" type="clock|power|ground|analog"                   #
#         status="covered|fixed|placed" is_special=1 >                       #
#      <Port>                                                                #
#        <Pref x=1 y=2 side="N|S|W|E|U|D" width=w depth=d orientation=val /> #
#        <Via name="via_name" x=1 y=2 BotMask=2 CutMask=1 TopMask=2 />...  #
#        <Layer id=id spacing=1.2 drw=1.2>                                   #
#          <Box llx=1 lly=2 urx=3 ury=4 /> ...                               #
#          <Poly points=nr x0=1 y0=1 x1=2 y2=2 ...           />              #
#        </Layer> ...                                                        #
#      </Port>  ...                                                          #
#      <NETEXPR>                                                             #
#        ground VSS                                                          #
#      </NETEXPR> ...                                                        #
#      <Antenna model=num type="name" value=float_num layer=num /> ...       #
#    </Pin> ...                                                              #
#  </IOPins>                                                                 #
##############################################################################

<IOPins>
  <Pin name="CLK" >
  </Pin>
  <Pin name="D[159]" >
  </Pin>
  <Pin name="D[158]" >
  </Pin>
  <Pin name="D[157]" >
  </Pin>
  <Pin name="D[156]" >
  </Pin>
  <Pin name="D[155]" >
  </Pin>
  <Pin name="D[154]" >
  </Pin>
  <Pin name="D[153]" >
  </Pin>
  <Pin name="D[152]" >
  </Pin>
  <Pin name="D[151]" >
  </Pin>
  <Pin name="D[150]" >
  </Pin>
  <Pin name="D[149]" >
  </Pin>
  <Pin name="D[148]" >
  </Pin>
  <Pin name="D[147]" >
  </Pin>
  <Pin name="D[146]" >
  </Pin>
  <Pin name="D[145]" >
  </Pin>
  <Pin name="D[144]" >
  </Pin>
  <Pin name="D[143]" >
  </Pin>
  <Pin name="D[142]" >
  </Pin>
  <Pin name="D[141]" >
  </Pin>
  <Pin name="D[140]" >
  </Pin>
  <Pin name="D[139]" >
  </Pin>
  <Pin name="D[138]" >
  </Pin>
  <Pin name="D[137]" >
  </Pin>
  <Pin name="D[136]" >
  </Pin>
  <Pin name="D[135]" >
  </Pin>
  <Pin name="D[134]" >
  </Pin>
  <Pin name="D[133]" >
  </Pin>
  <Pin name="D[132]" >
  </Pin>
  <Pin name="D[131]" >
  </Pin>
  <Pin name="D[130]" >
  </Pin>
  <Pin name="D[129]" >
  </Pin>
  <Pin name="D[128]" >
  </Pin>
  <Pin name="D[127]" >
  </Pin>
  <Pin name="D[126]" >
  </Pin>
  <Pin name="D[125]" >
  </Pin>
  <Pin name="D[124]" >
  </Pin>
  <Pin name="D[123]" >
  </Pin>
  <Pin name="D[122]" >
  </Pin>
  <Pin name="D[121]" >
  </Pin>
  <Pin name="D[120]" >
  </Pin>
  <Pin name="D[119]" >
  </Pin>
  <Pin name="D[118]" >
  </Pin>
  <Pin name="D[117]" >
  </Pin>
  <Pin name="D[116]" >
  </Pin>
  <Pin name="D[115]" >
  </Pin>
  <Pin name="D[114]" >
  </Pin>
  <Pin name="D[113]" >
  </Pin>
  <Pin name="D[112]" >
  </Pin>
  <Pin name="D[111]" >
  </Pin>
  <Pin name="D[110]" >
  </Pin>
  <Pin name="D[109]" >
  </Pin>
  <Pin name="D[108]" >
  </Pin>
  <Pin name="D[107]" >
  </Pin>
  <Pin name="D[106]" >
  </Pin>
  <Pin name="D[105]" >
  </Pin>
  <Pin name="D[104]" >
  </Pin>
  <Pin name="D[103]" >
  </Pin>
  <Pin name="D[102]" >
  </Pin>
  <Pin name="D[101]" >
  </Pin>
  <Pin name="D[100]" >
  </Pin>
  <Pin name="D[99]" >
  </Pin>
  <Pin name="D[98]" >
  </Pin>
  <Pin name="D[97]" >
  </Pin>
  <Pin name="D[96]" >
  </Pin>
  <Pin name="D[95]" >
  </Pin>
  <Pin name="D[94]" >
  </Pin>
  <Pin name="D[93]" >
  </Pin>
  <Pin name="D[92]" >
  </Pin>
  <Pin name="D[91]" >
  </Pin>
  <Pin name="D[90]" >
  </Pin>
  <Pin name="D[89]" >
  </Pin>
  <Pin name="D[88]" >
  </Pin>
  <Pin name="D[87]" >
  </Pin>
  <Pin name="D[86]" >
  </Pin>
  <Pin name="D[85]" >
  </Pin>
  <Pin name="D[84]" >
  </Pin>
  <Pin name="D[83]" >
  </Pin>
  <Pin name="D[82]" >
  </Pin>
  <Pin name="D[81]" >
  </Pin>
  <Pin name="D[80]" >
  </Pin>
  <Pin name="D[79]" >
  </Pin>
  <Pin name="D[78]" >
  </Pin>
  <Pin name="D[77]" >
  </Pin>
  <Pin name="D[76]" >
  </Pin>
  <Pin name="D[75]" >
  </Pin>
  <Pin name="D[74]" >
  </Pin>
  <Pin name="D[73]" >
  </Pin>
  <Pin name="D[72]" >
  </Pin>
  <Pin name="D[71]" >
  </Pin>
  <Pin name="D[70]" >
  </Pin>
  <Pin name="D[69]" >
  </Pin>
  <Pin name="D[68]" >
  </Pin>
  <Pin name="D[67]" >
  </Pin>
  <Pin name="D[66]" >
  </Pin>
  <Pin name="D[65]" >
  </Pin>
  <Pin name="D[64]" >
  </Pin>
  <Pin name="D[63]" >
  </Pin>
  <Pin name="D[62]" >
  </Pin>
  <Pin name="D[61]" >
  </Pin>
  <Pin name="D[60]" >
  </Pin>
  <Pin name="D[59]" >
  </Pin>
  <Pin name="D[58]" >
  </Pin>
  <Pin name="D[57]" >
  </Pin>
  <Pin name="D[56]" >
  </Pin>
  <Pin name="D[55]" >
  </Pin>
  <Pin name="D[54]" >
  </Pin>
  <Pin name="D[53]" >
  </Pin>
  <Pin name="D[52]" >
  </Pin>
  <Pin name="D[51]" >
  </Pin>
  <Pin name="D[50]" >
  </Pin>
  <Pin name="D[49]" >
  </Pin>
  <Pin name="D[48]" >
  </Pin>
  <Pin name="D[47]" >
  </Pin>
  <Pin name="D[46]" >
  </Pin>
  <Pin name="D[45]" >
  </Pin>
  <Pin name="D[44]" >
  </Pin>
  <Pin name="D[43]" >
  </Pin>
  <Pin name="D[42]" >
  </Pin>
  <Pin name="D[41]" >
  </Pin>
  <Pin name="D[40]" >
  </Pin>
  <Pin name="D[39]" >
  </Pin>
  <Pin name="D[38]" >
  </Pin>
  <Pin name="D[37]" >
  </Pin>
  <Pin name="D[36]" >
  </Pin>
  <Pin name="D[35]" >
  </Pin>
  <Pin name="D[34]" >
  </Pin>
  <Pin name="D[33]" >
  </Pin>
  <Pin name="D[32]" >
  </Pin>
  <Pin name="D[31]" >
  </Pin>
  <Pin name="D[30]" >
  </Pin>
  <Pin name="D[29]" >
  </Pin>
  <Pin name="D[28]" >
  </Pin>
  <Pin name="D[27]" >
  </Pin>
  <Pin name="D[26]" >
  </Pin>
  <Pin name="D[25]" >
  </Pin>
  <Pin name="D[24]" >
  </Pin>
  <Pin name="D[23]" >
  </Pin>
  <Pin name="D[22]" >
  </Pin>
  <Pin name="D[21]" >
  </Pin>
  <Pin name="D[20]" >
  </Pin>
  <Pin name="D[19]" >
  </Pin>
  <Pin name="D[18]" >
  </Pin>
  <Pin name="D[17]" >
  </Pin>
  <Pin name="D[16]" >
  </Pin>
  <Pin name="D[15]" >
  </Pin>
  <Pin name="D[14]" >
  </Pin>
  <Pin name="D[13]" >
  </Pin>
  <Pin name="D[12]" >
  </Pin>
  <Pin name="D[11]" >
  </Pin>
  <Pin name="D[10]" >
  </Pin>
  <Pin name="D[9]" >
  </Pin>
  <Pin name="D[8]" >
  </Pin>
  <Pin name="D[7]" >
  </Pin>
  <Pin name="D[6]" >
  </Pin>
  <Pin name="D[5]" >
  </Pin>
  <Pin name="D[4]" >
  </Pin>
  <Pin name="D[3]" >
  </Pin>
  <Pin name="D[2]" >
  </Pin>
  <Pin name="D[1]" >
  </Pin>
  <Pin name="D[0]" >
  </Pin>
  <Pin name="Q[159]" >
  </Pin>
  <Pin name="Q[158]" >
  </Pin>
  <Pin name="Q[157]" >
  </Pin>
  <Pin name="Q[156]" >
  </Pin>
  <Pin name="Q[155]" >
  </Pin>
  <Pin name="Q[154]" >
  </Pin>
  <Pin name="Q[153]" >
  </Pin>
  <Pin name="Q[152]" >
  </Pin>
  <Pin name="Q[151]" >
  </Pin>
  <Pin name="Q[150]" >
  </Pin>
  <Pin name="Q[149]" >
  </Pin>
  <Pin name="Q[148]" >
  </Pin>
  <Pin name="Q[147]" >
  </Pin>
  <Pin name="Q[146]" >
  </Pin>
  <Pin name="Q[145]" >
  </Pin>
  <Pin name="Q[144]" >
  </Pin>
  <Pin name="Q[143]" >
  </Pin>
  <Pin name="Q[142]" >
  </Pin>
  <Pin name="Q[141]" >
  </Pin>
  <Pin name="Q[140]" >
  </Pin>
  <Pin name="Q[139]" >
  </Pin>
  <Pin name="Q[138]" >
  </Pin>
  <Pin name="Q[137]" >
  </Pin>
  <Pin name="Q[136]" >
  </Pin>
  <Pin name="Q[135]" >
  </Pin>
  <Pin name="Q[134]" >
  </Pin>
  <Pin name="Q[133]" >
  </Pin>
  <Pin name="Q[132]" >
  </Pin>
  <Pin name="Q[131]" >
  </Pin>
  <Pin name="Q[130]" >
  </Pin>
  <Pin name="Q[129]" >
  </Pin>
  <Pin name="Q[128]" >
  </Pin>
  <Pin name="Q[127]" >
  </Pin>
  <Pin name="Q[126]" >
  </Pin>
  <Pin name="Q[125]" >
  </Pin>
  <Pin name="Q[124]" >
  </Pin>
  <Pin name="Q[123]" >
  </Pin>
  <Pin name="Q[122]" >
  </Pin>
  <Pin name="Q[121]" >
  </Pin>
  <Pin name="Q[120]" >
  </Pin>
  <Pin name="Q[119]" >
  </Pin>
  <Pin name="Q[118]" >
  </Pin>
  <Pin name="Q[117]" >
  </Pin>
  <Pin name="Q[116]" >
  </Pin>
  <Pin name="Q[115]" >
  </Pin>
  <Pin name="Q[114]" >
  </Pin>
  <Pin name="Q[113]" >
  </Pin>
  <Pin name="Q[112]" >
  </Pin>
  <Pin name="Q[111]" >
  </Pin>
  <Pin name="Q[110]" >
  </Pin>
  <Pin name="Q[109]" >
  </Pin>
  <Pin name="Q[108]" >
  </Pin>
  <Pin name="Q[107]" >
  </Pin>
  <Pin name="Q[106]" >
  </Pin>
  <Pin name="Q[105]" >
  </Pin>
  <Pin name="Q[104]" >
  </Pin>
  <Pin name="Q[103]" >
  </Pin>
  <Pin name="Q[102]" >
  </Pin>
  <Pin name="Q[101]" >
  </Pin>
  <Pin name="Q[100]" >
  </Pin>
  <Pin name="Q[99]" >
  </Pin>
  <Pin name="Q[98]" >
  </Pin>
  <Pin name="Q[97]" >
  </Pin>
  <Pin name="Q[96]" >
  </Pin>
  <Pin name="Q[95]" >
  </Pin>
  <Pin name="Q[94]" >
  </Pin>
  <Pin name="Q[93]" >
  </Pin>
  <Pin name="Q[92]" >
  </Pin>
  <Pin name="Q[91]" >
  </Pin>
  <Pin name="Q[90]" >
  </Pin>
  <Pin name="Q[89]" >
  </Pin>
  <Pin name="Q[88]" >
  </Pin>
  <Pin name="Q[87]" >
  </Pin>
  <Pin name="Q[86]" >
  </Pin>
  <Pin name="Q[85]" >
  </Pin>
  <Pin name="Q[84]" >
  </Pin>
  <Pin name="Q[83]" >
  </Pin>
  <Pin name="Q[82]" >
  </Pin>
  <Pin name="Q[81]" >
  </Pin>
  <Pin name="Q[80]" >
  </Pin>
  <Pin name="Q[79]" >
  </Pin>
  <Pin name="Q[78]" >
  </Pin>
  <Pin name="Q[77]" >
  </Pin>
  <Pin name="Q[76]" >
  </Pin>
  <Pin name="Q[75]" >
  </Pin>
  <Pin name="Q[74]" >
  </Pin>
  <Pin name="Q[73]" >
  </Pin>
  <Pin name="Q[72]" >
  </Pin>
  <Pin name="Q[71]" >
  </Pin>
  <Pin name="Q[70]" >
  </Pin>
  <Pin name="Q[69]" >
  </Pin>
  <Pin name="Q[68]" >
  </Pin>
  <Pin name="Q[67]" >
  </Pin>
  <Pin name="Q[66]" >
  </Pin>
  <Pin name="Q[65]" >
  </Pin>
  <Pin name="Q[64]" >
  </Pin>
  <Pin name="Q[63]" >
  </Pin>
  <Pin name="Q[62]" >
  </Pin>
  <Pin name="Q[61]" >
  </Pin>
  <Pin name="Q[60]" >
  </Pin>
  <Pin name="Q[59]" >
  </Pin>
  <Pin name="Q[58]" >
  </Pin>
  <Pin name="Q[57]" >
  </Pin>
  <Pin name="Q[56]" >
  </Pin>
  <Pin name="Q[55]" >
  </Pin>
  <Pin name="Q[54]" >
  </Pin>
  <Pin name="Q[53]" >
  </Pin>
  <Pin name="Q[52]" >
  </Pin>
  <Pin name="Q[51]" >
  </Pin>
  <Pin name="Q[50]" >
  </Pin>
  <Pin name="Q[49]" >
  </Pin>
  <Pin name="Q[48]" >
  </Pin>
  <Pin name="Q[47]" >
  </Pin>
  <Pin name="Q[46]" >
  </Pin>
  <Pin name="Q[45]" >
  </Pin>
  <Pin name="Q[44]" >
  </Pin>
  <Pin name="Q[43]" >
  </Pin>
  <Pin name="Q[42]" >
  </Pin>
  <Pin name="Q[41]" >
  </Pin>
  <Pin name="Q[40]" >
  </Pin>
  <Pin name="Q[39]" >
  </Pin>
  <Pin name="Q[38]" >
  </Pin>
  <Pin name="Q[37]" >
  </Pin>
  <Pin name="Q[36]" >
  </Pin>
  <Pin name="Q[35]" >
  </Pin>
  <Pin name="Q[34]" >
  </Pin>
  <Pin name="Q[33]" >
  </Pin>
  <Pin name="Q[32]" >
  </Pin>
  <Pin name="Q[31]" >
  </Pin>
  <Pin name="Q[30]" >
  </Pin>
  <Pin name="Q[29]" >
  </Pin>
  <Pin name="Q[28]" >
  </Pin>
  <Pin name="Q[27]" >
  </Pin>
  <Pin name="Q[26]" >
  </Pin>
  <Pin name="Q[25]" >
  </Pin>
  <Pin name="Q[24]" >
  </Pin>
  <Pin name="Q[23]" >
  </Pin>
  <Pin name="Q[22]" >
  </Pin>
  <Pin name="Q[21]" >
  </Pin>
  <Pin name="Q[20]" >
  </Pin>
  <Pin name="Q[19]" >
  </Pin>
  <Pin name="Q[18]" >
  </Pin>
  <Pin name="Q[17]" >
  </Pin>
  <Pin name="Q[16]" >
  </Pin>
  <Pin name="Q[15]" >
  </Pin>
  <Pin name="Q[14]" >
  </Pin>
  <Pin name="Q[13]" >
  </Pin>
  <Pin name="Q[12]" >
  </Pin>
  <Pin name="Q[11]" >
  </Pin>
  <Pin name="Q[10]" >
  </Pin>
  <Pin name="Q[9]" >
  </Pin>
  <Pin name="Q[8]" >
  </Pin>
  <Pin name="Q[7]" >
  </Pin>
  <Pin name="Q[6]" >
  </Pin>
  <Pin name="Q[5]" >
  </Pin>
  <Pin name="Q[4]" >
  </Pin>
  <Pin name="Q[3]" >
  </Pin>
  <Pin name="Q[2]" >
  </Pin>
  <Pin name="Q[1]" >
  </Pin>
  <Pin name="Q[0]" >
  </Pin>
  <Pin name="CEN" >
  </Pin>
  <Pin name="WEN" >
  </Pin>
  <Pin name="A[3]" >
  </Pin>
  <Pin name="A[2]" >
  </Pin>
  <Pin name="A[1]" >
  </Pin>
  <Pin name="A[0]" >
  </Pin>
</IOPins>

#####################################################################
#  <Property>                                                       #
#     <obj_type name="inst_name" >                                  #
#       <prop name="name" type=type_name value=val />               #
#       <Attr name="name" type=type_name value=val />               #
#     </obj_type>                                                   #
#  </Property>                                                      #
#  where:                                                           #
#       type is data type: Box, String, Int, PTR, Loc, double, Bits #
#       obj_type are: inst, Design, instTerm, Bump, cell, net       #
#####################################################################
<Properties>
  <Design name="sram_w16_out">
  </Design>
</Properties>

################################################################################
#  NetProperties: <net_name> [-special] [-def_prop {int|dbl|str} <value>]...   #
################################################################################

##################################################################################
#    Feedthru info:                                                              #
# <Feedthrus>                                                                    #
#   <Feedthru>                                                                   #
#       <tsv llx=n lly=n urx=n ury=n />                                          #
#       <stackvia layer=z llx=n lly=n urx=n ury=n />                             #
#       <bump front=name back=name  />                                           #
#   </Feedthru>                                                                  #
#   <Feedthru>                                                                   #
#   <...>                                                                        #
#   </Feedthru>                                                                  #
# </Feedthrus>                                                                   #
################################################################################
